# Generated by Django 4.0.5 on 2022-06-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traintest',
            name='travel_time',
        ),
    ]
