# Generated by Django 4.0.5 on 2023-03-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_city_options_alter_city_name'),
        ('trains', '0003_alter_traintest_from_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['travel_time'], 'verbose_name': 'Потяг', 'verbose_name_plural': 'Поїзди'},
        ),
        migrations.AlterField(
            model_name='train',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='cities.city', verbose_name='З якого міста'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер потягу'),
        ),
        migrations.AlterField(
            model_name='train',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='cities.city', verbose_name='В яке місто'),
        ),
        migrations.AlterField(
            model_name='train',
            name='travel_time',
            field=models.PositiveSmallIntegerField(verbose_name='Час в дорозі'),
        ),
        migrations.AlterField(
            model_name='traintest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='cities.city', verbose_name='З якого  міста'),
        ),
        migrations.AlterField(
            model_name='traintest',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер потягу'),
        ),
    ]
