# Generated by Django 4.0.5 on 2023-03-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_alter_train_options_alter_train_from_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainTest',
        ),
    ]
