# Generated by Django 4.0.5 on 2023-04-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0005_delete_traintest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['from_city'], 'verbose_name': 'Потяг', 'verbose_name_plural': 'Поїзди'},
        ),
    ]
