# Generated by Django 4.0.5 on 2023-03-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_alter_traintest_from_city'),
        ('cities', '0004_alter_city_options_alter_city_name'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['travel_times'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршрути'},
        ),
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from_city_set', to='cities.city', verbose_name='З якого міста'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва маршруту'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_city_set', to='cities.city', verbose_name='В яке місто'),
        ),
        migrations.AlterField(
            model_name='route',
            name='trains',
            field=models.ManyToManyField(to='trains.train', verbose_name='Список поїздів'),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_times',
            field=models.PositiveSmallIntegerField(verbose_name='Загальний час у дорозі'),
        ),
    ]
